spring:
  application:
    name: trusticket-payment
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true #show sql
        default_batch_fetch_size: 100
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      properties:
        bootstrap.servers: ${SPRING_KAFKA_ADMIN_PROPERTIES_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    discovery:
      enabled: false


# Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /login

# Exception handler

error:
  printStackTrace: true # Stack trace ?? ??
  printStackTraceLine: 10 # Stack trace ?? ? ?

server:
  port: 8080