version: "3.7"
services:
  trusticket-payment-database:
    platform: linux/x86_64
    image: mariadb:10.11.2
    environment:
      MYSQL_DATABASE: "trusticket-payment-db"
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - 4005:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

 